import type { Day } from './schedule.types';

export const days: Day[] = [
  {
    date: '2026-08-31',
    dayName: 'Lunes',
    dayNum: '31',
    month: 'Ago',
    theme: 'Inauguración',
    activities: [
      {
        time: '06:30',
        duration: '1h 30min',
        title: 'Desayuno',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 500,
      },
      {
        time: '08:00',
        duration: '1h 20min',
        title: 'Inauguración',
        // speaker: 'Rector UNSM',
        location: 'UNSM',
        type: 'ceremonia',
        // capacity: 500,
        description:
          'Acto de apertura con autoridades universitarias y representantes nacionales.',
      },
      {
        time: '09:20',
        duration: '40min',
        title: 'Ponencia 1',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '10:00',
        duration: '40min',
        title: 'Ponencia 2',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 300,
      },
      {
        time: '10:40',
        duration: '1h 20min',
        title: 'Foro 1',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 40,
        // description: 'Prácticas de análisis de muestras de suelo amazónico.',
      },
      {
        time: '12:00',
        duration: '2h',
        title: 'Almuerzo',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 600,
        // description:
        //   'Inauguración de stands de emprendedores y proyectos universitarios.',
      },
      {
        time: '14:00',
        duration: '1h',
        title: 'Tiempo de descanso y reunión de delegados',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '15:00',
        duration: '3h 30min',
        title: 'Deporte',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '18:30',
        duration: '1h 30min',
        title: 'Cena',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '20:00',
        duration: '2h',
        title: 'Deporte',
        location: 'UNSM',
        type: 'cultural',
      },
    ],
  },
  {
    date: '2026-09-01',
    dayName: 'Martes',
    dayNum: '01',
    month: 'Sep',
    theme: 'Visita Técnica',
    activities: [
      {
        time: '06:30',
        duration: '1h 30min',
        title: 'Desayuno',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 500,
      },
      {
        time: '08:00',
        duration: '40min',
        title: 'Ponencia 3',
        // speaker: 'Rector UNSM',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 500,
        // description:
        //   'Acto de apertura con autoridades universitarias y representantes nacionales.',
      },
      {
        time: '08:40',
        duration: '40min',
        title: 'Ponencia 4',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '09:20',
        duration: '40min',
        title: 'Ponencia 5',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '10:00',
        duration: '40min',
        title: 'Ponencia 6',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 300,
      },
      {
        time: '10:40',
        duration: '1h 20min',
        title: 'Foro 2',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 40,
        // description: 'Prácticas de análisis de muestras de suelo amazónico.',
      },
      {
        time: '12:00',
        duration: '2h',
        title: 'Almuerzo',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 600,
        // description:
        //   'Inauguración de stands de emprendedores y proyectos universitarios.',
      },
      {
        time: '14:00',
        duration: '1h',
        title: 'Tiempo de descanso y reunión de delegados',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '15:00',
        duration: '3h 30min',
        title: 'Visita técnica',
        location: 'UNSM',
        type: 'laboratorio',
      },
      {
        time: '18:30',
        duration: '1h 30min',
        title: 'Cena',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '20:00',
        duration: '2h',
        title: 'Deporte',
        location: 'UNSM',
        type: 'cultural',
      },
    ],
  },
  {
    date: '2026-09-02',
    dayName: 'Miercoles',
    dayNum: '02',
    month: 'Sep',
    theme: 'Pasacalle y Unsha',
    activities: [
      {
        time: '06:30',
        duration: '1h 30min',
        title: 'Desayuno',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 500,
      },
      {
        time: '08:00',
        duration: '40min',
        title: 'Ponencia 7',
        // speaker: 'Rector UNSM',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 500,
        // description:
        //   'Acto de apertura con autoridades universitarias y representantes nacionales.',
      },
      {
        time: '08:40',
        duration: '40min',
        title: 'Ponencia 8',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '09:20',
        duration: '40min',
        title: 'Ponencia 9',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '10:00',
        duration: '40min',
        title: 'Ponencia 10',
        location: 'UNSM',
        type: 'ponencia',
        // capacity: 300,
      },
      {
        time: '10:40',
        duration: '1h 20min',
        title: 'Foro 3',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 40,
        // description: 'Prácticas de análisis de muestras de suelo amazónico.',
      },
      {
        time: '12:00',
        duration: '2h',
        title: 'Almuerzo',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 600,
        // description:
        //   'Inauguración de stands de emprendedores y proyectos universitarios.',
      },
      {
        time: '14:00',
        duration: '1h',
        title: 'Tiempo de descanso y reunión de delegados',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '15:00',
        duration: '3h 30min',
        title: 'Pasacalle y unsha',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '18:30',
        duration: '1h 30min',
        title: 'Cena',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '20:00',
        duration: '2h',
        title: 'Deporte',
        location: 'UNSM',
        type: 'cultural',
      },
    ],
  },
  {
    date: '2026-09-03',
    dayName: 'Jueves',
    dayNum: '03',
    month: 'Sep',
    theme: 'Expo feria y Concursos',
    activities: [
      {
        time: '06:30',
        duration: '1h 30min',
        title: 'Desayuno',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 500,
      },
      {
        time: '08:00',
        duration: '40min',
        title: 'Inauguración de expo feria',
        // speaker: 'Rector UNSM',
        location: 'UNSM',
        type: 'ceremonia',
        // capacity: 500,
        // description:
        //   'Acto de apertura con autoridades universitarias y representantes nacionales.',
      },
      {
        time: '08:40',
        duration: '3h 20min',
        title: 'Concurso de Innovación e investigación',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'laboratorio',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '12:00',
        duration: '2h',
        title: 'Almuerzo',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 600,
        // description:
        //   'Inauguración de stands de emprendedores y proyectos universitarios.',
      },
      {
        time: '14:00',
        duration: '1h',
        title: 'Tiempo de descanso y reunión de delegados',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '15:00',
        duration: '3h 30min',
        title: 'Expo feria: emprendimiento y concursos',
        location: 'UNSM',
        type: 'feria',
      },
      {
        time: '18:30',
        duration: '1h 30min',
        title: 'Cena',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '20:00',
        duration: '2h',
        title: 'Deporte',
        location: 'UNSM',
        type: 'cultural',
      },
    ],
  },
  {
    date: '2026-09-04',
    dayName: 'Viernes',
    dayNum: '04',
    month: 'Sep',
    theme: 'Ginkana y Clausura',
    activities: [
      {
        time: '06:30',
        duration: '1h 30min',
        title: 'Desayuno',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 500,
      },
      {
        time: '08:00',
        duration: '1h 20min',
        title: 'Examen académico',
        // speaker: 'Rector UNSM',
        location: 'UNSM',
        type: 'laboratorio',
        // capacity: 500,
        // description:
        //   'Acto de apertura con autoridades universitarias y representantes nacionales.',
      },
      {
        time: '09:20',
        duration: '2h 40min',
        title: 'Ginkana agronómica',
        // speaker: 'Dr. Julio Rengifo Paredes',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 400,
        // description:
        //   'Perspectivas sobre el rol del agrónomo en la seguridad alimentaria peruana.',
      },
      {
        time: '12:00',
        duration: '2h',
        title: 'Almuerzo',
        location: 'UNSM',
        type: 'cultural',
        // capacity: 600,
        // description:
        //   'Inauguración de stands de emprendedores y proyectos universitarios.',
      },
      {
        time: '14:00',
        duration: '1h',
        title: 'Tiempo de descanso y reunión de delegados',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '15:00',
        duration: '3h 30min',
        title: 'Clausura',
        location: 'UNSM',
        type: 'ceremonia',
      },
      {
        time: '18:30',
        duration: '1h 30min',
        title: 'Cena',
        location: 'UNSM',
        type: 'cultural',
      },
      {
        time: '20:00',
        duration: '2h',
        title: 'Deporte',
        location: 'UNSM',
        type: 'cultural',
      },
    ],
  },
];
